[package]
name = "Nugget"
version = "0.1.0"
edition = "2024"

[dependencies]
poise = "=0.6.1"
tokio = { version = "1.44.1", features = ["full"] }
toml = "0.8.20"
rand = "0.9.0"
serde = "1.0.219"
serde_derive = "1.0.219"
lazy_static = "1.5.0"
