name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable

    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-gnu --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rust-linux-release
        path: target/x86_64-unknown-linux-gnu/release/Nugget
